# Generated by Django 3.1.6 on 2021-06-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catogery',
            name='descreption',
            field=models.CharField(max_length=100),
        ),
    ]
